<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AsesmenKandungan extends Model
{
    protected $fillable = [
        'nama_dokumen',
        'rm_pasien',
        'rujukan', 
        'tanggal_datang', 
        'jam_datang',
        'pendarahan',
        'keputihan', 
        'nyeri', 
        'benjolan',
        'riwayat_haid', 
        'menars_usia', 
        'lama_haid', 
        'nyeri_haid', 
        'nyeri_haid_saat', 
        'jumlah_pembalut',
        'warna_haid', 
        'konsistensi_haid',
        'gangguan_seksual',
        'kb_jenis', 
        'kb_lama',
        'obathormon_pernah', 
        'penyakit_jantung',
        'penyakit_paru',
        'penyakit_infeksi',
        'penyakit_metabolik',
        'penyakit_operasi', 
        'faktor_lingkungan',
        'riwayat_pengobatan', 
        'alergi', 
        'kesadaran', 
        'tensi', 
        'nadi', 
        'suhu_tr', 
        'suhu_ta', 
        'respiration_rate', 
        'keadaan', 
        'keadaan_kepala', 
        'keadaan_dada',
        'keadaan_perut', 
        'ekstremitas',
        'vt_p',
        'vt_cu', 
        'vt_ap_ka', 
        'vt_ap_ki', 
        'vt_cd',
        'inspekulo', 
        'pungsi_douglas', 
        'ultrasonografi',
        'ct_scan', 
        'laboratorium', 
        'sketsa', 
        'assesmen', 
        'med_1', 
        'med_2', 
        'med_3', 
        'med_4', 
        'med_5', 
        'dokter_pj'     
    ];
}
